### ISSUE TITLE
sitecustomize.py: an unexpected error anywhere in import_distro() leaves the agent active and retried by every child process

### ISSUE THREAD

**Issue by ocelotl** [open-telemetry/opentelemetry-packaging#98]
`sitecustomize.py` guards individual operations carefully, and then calls `import_distro()` with nothing around it:

https://github.com/open-telemetry/opentelemetry-packaging/blob/f569839889abe2f1cee92fb6a12794ccfa7e3116/packaging/common/python/sitecustomize.py#L337

An exception from anywhere in that call that is not one of the four narrow `try` blocks escapes into `site.execsitecustomize()`, and the process ends up in the exact state every guard in the file exists to prevent. This is the same failure class as #93, reached through paths #94 does not cover. #93 closed one door into that state; this is the door frame.

## Reproduction

The most reachable trigger is `dist._path` on line 111. That attribute is private and only `PathDistribution` has it, so a distribution surfaced by any other finder raises `AttributeError`. Nothing catches it, and nothing would notice in review either: the only test that exercises the line assigns `_path` to a `MagicMock` (`test_sitecustomize.py:396`), which accepts any attribute.

I reproduced it with the packaged script, unmodified, on `python:3.13-slim`. A `.pth` file installed in `site-packages` replaces `importlib.metadata.distributions` with one returning a `Distribution` that has `metadata["Name"] == "opentelemetry-sdk"` and no `_path`. The `.pth` is only a way to get in front of `sitecustomize.py`, since `site` processes `site-packages/*.pth` before `execsitecustomize()`.

```
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: '_DistributionWithoutPath' object has no attribute '_path'
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: '_DistributionWithoutPath' object has no attribute '_path'
  child ran to completion
--- state left behind in the parent ---
  site on sys.path:                                False
  site in os.environ['PYTHONPATH']:                True
  PYTHON_AUTO_INSTRUMENTATION_AGENT_PATH_PREFIX:   '/usr/lib/opentelemetry/python'
  opentelemetry modules imported:                  0
APP RAN TO COMPLETION
exit code: 0
```

| | expected on a deactivation | actual |
|---|---|---|
| site in `PYTHONPATH` | removed | still present |
| `PYTHON_AUTO_INSTRUMENTATION_AGENT_PATH_PREFIX` | cleared | still set |
| site on `sys.path` | removed | removed, but see below |
| `[opentelemetry-python-autoinstrumentation]` lines | 1 | 0 |
| child process repeats the failure | no | yes |
| application exit code | 0 | 0 |

## Why it matters

1. **No message that names the agent.** `site.execsitecustomize()` catches the exception and prints one line with no `[opentelemetry-python-autoinstrumentation]` prefix and no traceback unless `PYTHONVERBOSE` is set. Anything grepping for the agent's marker, including this repository's own container tests, sees silence.

2. **The deactivation never runs.** `PYTHONPATH` keeps the site and the injector prefix stays set, so every child process that execs a new interpreter repeats the failure and reprints the line. The second error line above is the child. On a gunicorn or celery deployment that multiplies by the worker count. This is exactly what `_self_deactivate` exists to prevent.

3. **`sys.path` is left inconsistent.** The failure lands between the removal on line 291 and the re-append on line 299, so the parent process has neither instrumentation nor the bundle on `sys.path`. #93's failure at least left the bundle importable. Here an application that legitimately imports something from the bundle after startup cannot.

4. **The application is unharmed and exits 0**, which is the only good news, and is what lets this go unnoticed indefinitely.

## Proposed fix

An outer guard whose own reporting is guarded, because the thing that failed can be the diagnostics channel:

```python
try:
    import_distro()
except Exception as unexpected_error:
    try:
        _self_deactivate(dirname(__file__))
        _print_cannot_auto_instrument_message(
            "unexpected error while deciding whether to auto-instrument: {}: {}".format(
                type(unexpected_error).__name__, unexpected_error))
    except Exception:
        pass
```

Same reproduction against the patched script:

```
[opentelemetry-python-autoinstrumentation] WARN: cannot auto-instrument Python process: unexpected error while
deciding whether to auto-instrument: AttributeError: '_DistributionWithoutPath' object has no attribute '_path' [/app.py]
  site in os.environ['PYTHONPATH']:                False
  PYTHON_AUTO_INSTRUMENTATION_AGENT_PATH_PREFIX:   ''
```

One prefixed line, a clean deactivation, no child retry. It also compiles on `python:2.7-slim`, so the parse contract on line 11 holds.

## The specific holes the guard covers today

Worth listing, because the guard is the general fix and these are individually fixable:

- **`dist._path`, line 111.** Private, and only on `PathDistribution`. Worth fixing at the source: `dist.locate_file("")` is the public equivalent that every `Distribution` implements.
- **`importlib.metadata.distributions()`, line 108.** Enumerates every distribution on `sys.path` and parses their metadata.
- **`from packaging.requirements import Requirement`, lines 143-144.** Resolves against an application-supplied `packaging` whenever the application has one, because the site is appended last on line 299 so that the application's versions win. An old or broken `packaging` raises `ImportError` here.
- **`import subprocess`, line 205**, and `import logging` if #96 lands, for the same reason: neither is in a bare interpreter's `sys.modules`, so both are shadowable from `PYTHONPATH`.

None of these is exotic enough to leave uncovered, and the guard costs four lines.
